### ISSUE TITLE
风格指南

### ISSUE THREAD

**Issue by daisybaicai** [daisybaicai/Blog#26]
# 风格指南

组件命名

- 组件，容器，页面都需要定义成文件夹的形式，主component定义为index.js
- 命名为驼峰AwesomeCard

项目结构

- 至少三层，page,container,component

代码规范

- 解构 对象不超过两层 

- 命名规范，需要有意义

  ```javascript
  const getNumberValidation = message => value => !onlyNumbersRegex.test(value) && message
  ```

- 对于常量定义，枚举或者定义成可以解释的变量

  ```javascript
  const DAY_IN_MILLISECONDS = 86400000
  
  setTimeout(doSomething, DAY_IN_MILLISECONDS)
  ```

- 一行不超过2个props

  ```react
  <button
    className="aLongSpecificClassNameWithLasers"
    disabled={loading}
    onClick={() => null}
    type="submit"
  >
    Click here
  </button>
  ```

css规范

- 驼峰

  ```less
  .circleBullet {
    list-style-type: disc;
  }
  ```

- 不要把id和tag作为根选择器

  (better)

  ```less
  .container > img {
    background-color: #CCCCCC;
  }
  ```

  

- css书写

  ```react
  import style from './style.css'
  
  const Input = ({ value, onChange, error }) =>
    <div className={classNames({ [style.error]: error })}>
      <input onChange={onChange} />
      <p>{error}</p>
    </div>
  
  export default Input
  ```

*参考*

- https://github.com/pagarme/react-style-guide
